name: Mirror to fuegoextremo/rewappFuego

on:
  push:
    branches:
      - main  # Solo ejecutar cuando se actualice main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo (leo-neutrondigital/rewapp)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Mirror repository
        run: |
          git config --global user.name 'Mirror Bot'
          git config --global user.email 'mirror@rewapp.com'
          
          git remote add mirror git@github.com:fuegoextremo/rewappFuego.git
          git push mirror main --force