name: Mirror to fuegoextremo/rewappFuego

on:
  push:
    branches:
      - main  # Solo ejecutar cuando se actualice main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo (leo-neutrondigital/rewapp)
        uses: actions/checkout@v3

      - name: Push to fuegoextremo/rewappFuego
        run: |
          git config --global user.name 'Mirror Bot'
          git config --global user.email 'noreply@github.com'

          # Usar el token directamente sin x-access-token prefix
          git remote add mirror https://${{ secrets.MIRROR_TOKEN }}@github.com/fuegoextremo/rewappFuego.git
          git push mirror main --force