name: Mirror to fuegoextremo/rewappFuego

on:
  push:
    branches:
      - main  # Solo ejecutar cuando se actualice main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo (leo-neutrondigital/rewapp)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://github.com/fuegoextremo/rewappFuego.git
          ssh_private_key: ${{ secrets.MIRROR_SSH_KEY }}